<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\City::create([ 'state_id' => 1,  'name' => 'Maroa'                               ]);
        App\City::create([ 'state_id' => 1,  'name' => 'Puerto Ayacucho'                     ]);
        App\City::create([ 'state_id' => 1,  'name' => 'San Fernando de Atabapo'             ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Anaco'                               ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Aragua de Barcelona'                 ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Barcelona'                           ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Boca de Uchire'                      ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Cantaura'                            ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Clarines'                            ]);
        App\City::create([ 'state_id' => 2,  'name' => 'El Chaparro'                         ]);
        App\City::create([ 'state_id' => 2,  'name' => 'El Pao Anzoátegui'                   ]);
        App\City::create([ 'state_id' => 2,  'name' => 'El Tigre'                            ]);
        App\City::create([ 'state_id' => 2,  'name' => 'El Tigrito'                          ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Guanape'                             ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Guanta'                              ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Lechería'                            ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Onoto'                               ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Pariaguán'                           ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Píritu'                              ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Puerto La Cruz'                      ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Puerto Píritu'                       ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Sabana de Uchire'                    ]);
        App\City::create([ 'state_id' => 2,  'name' => 'San Mateo Anzoátegui'                ]);
        App\City::create([ 'state_id' => 2,  'name' => 'San Pablo Anzoátegui'                ]);
        App\City::create([ 'state_id' => 2,  'name' => 'San Tomé'                            ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Santa Ana de Anzoátegui'             ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Santa Fe Anzoátegui'                 ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Santa Rosa'                          ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Soledad'                             ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Urica'                               ]);
        App\City::create([ 'state_id' => 2,  'name' => 'Valle de Guanape'                    ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Achaguas'                            ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Biruaca'                             ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Bruzual'                             ]);
        App\City::create([ 'state_id' => 3,  'name' => 'El Amparo'                           ]);
        App\City::create([ 'state_id' => 3,  'name' => 'El Nula'                             ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Elorza'                              ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Guasdualito'                         ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Mantecal'                            ]);
        App\City::create([ 'state_id' => 3,  'name' => 'Puerto Páez'                         ]);
        App\City::create([ 'state_id' => 3,  'name' => 'San Fernando de Apure'               ]);
        App\City::create([ 'state_id' => 3,  'name' => 'San Juan de Payara'                  ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Barbacoas'                           ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Cagua'                               ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Camatagua'                           ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Choroní'                             ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Colonia Tovar'                       ]);
        App\City::create([ 'state_id' => 4,  'name' => 'El Consejo'                          ]);
        App\City::create([ 'state_id' => 4,  'name' => 'La Victoria'                         ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Las Tejerías'                        ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Magdaleno'                           ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Maracay'                             ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Ocumare de La Costa'                 ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Palo Negro'                          ]);
        App\City::create([ 'state_id' => 4,  'name' => 'San Casimiro'                        ]);
        App\City::create([ 'state_id' => 4,  'name' => 'San Mateo'                           ]);
        App\City::create([ 'state_id' => 4,  'name' => 'San Sebastián'                       ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Santa Cruz de Aragua'                ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Tocorón'                             ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Turmero'                             ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Villa de Cura'                       ]);
        App\City::create([ 'state_id' => 4,  'name' => 'Zuata'                               ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Barinas'                             ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Barinitas'                           ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Barrancas'                           ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Calderas'                            ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Capitanejo'                          ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Ciudad Bolivia'                      ]);
        App\City::create([ 'state_id' => 5,  'name' => 'El Cantón'                           ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Las Veguitas'                        ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Libertad de Barinas'                 ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Sabaneta'                            ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Santa Bárbara de Barinas'            ]);
        App\City::create([ 'state_id' => 5,  'name' => 'Socopó'                              ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Caicara del Orinoco'                 ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Canaima'                             ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Ciudad Bolívar'                      ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Ciudad Piar'                         ]);
        App\City::create([ 'state_id' => 6,  'name' => 'El Callao'                           ]);
        App\City::create([ 'state_id' => 6,  'name' => 'El Dorado'                           ]);
        App\City::create([ 'state_id' => 6,  'name' => 'El Manteco'                          ]);
        App\City::create([ 'state_id' => 6,  'name' => 'El Palmar'                           ]);
        App\City::create([ 'state_id' => 6,  'name' => 'El Pao'                              ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Guasipati'                           ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Guri'                                ]);
        App\City::create([ 'state_id' => 6,  'name' => 'La Paragua'                          ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Matanzas'                            ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Puerto Ordaz'                        ]);
        App\City::create([ 'state_id' => 6,  'name' => 'San Félix'                           ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Santa Elena de Uairén'               ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Tumeremo'                            ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Unare'                               ]);
        App\City::create([ 'state_id' => 6,  'name' => 'Upata'                               ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Bejuma'                              ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Belén'                               ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Campo de Carabobo'                   ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Canoabo'                             ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Central Tacarigua'                   ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Chirgua'                             ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Ciudad Alianza'                      ]);
        App\City::create([ 'state_id' => 7,  'name' => 'El Palito'                           ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Guacara'                             ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Guigue'                              ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Las Trincheras'                      ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Los Guayos'                          ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Mariara'                             ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Miranda'                             ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Montalbán'                           ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Morón'                               ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Naguanagua'                          ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Puerto Cabello'                      ]);
        App\City::create([ 'state_id' => 7,  'name' => 'San Joaquín'                         ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Tocuyito'                            ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Urama'                               ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Valencia'                            ]);
        App\City::create([ 'state_id' => 7,  'name' => 'Vigirimita'                          ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Aguirre'                             ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Apartaderos Cojedes'                 ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Arismendi'                           ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Camuriquito'                         ]);
        App\City::create([ 'state_id' => 8,  'name' => 'El Baúl'                             ]);
        App\City::create([ 'state_id' => 8,  'name' => 'El Limón'                            ]);
        App\City::create([ 'state_id' => 8,  'name' => 'El Pao Cojedes'                      ]);
        App\City::create([ 'state_id' => 8,  'name' => 'El Socorro'                          ]);
        App\City::create([ 'state_id' => 8,  'name' => 'La Aguadita'                         ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Las Vegas'                           ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Libertad de Cojedes'                 ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Mapuey'                              ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Piñedo'                              ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Samancito'                           ]);
        App\City::create([ 'state_id' => 8,  'name' => 'San Carlos'                          ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Sucre'                               ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Tinaco'                              ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Tinaquillo'                          ]);
        App\City::create([ 'state_id' => 8,  'name' => 'Vallecito'                           ]);
        App\City::create([ 'state_id' => 9,  'name' => 'Tucupita'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Adícora'                             ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Boca de Aroa'                        ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Cabure'                              ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Capadare'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Capatárida'                          ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Chichiriviche'                       ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Churuguara'                          ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Coro'                                ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Cumarebo'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Dabajuro'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Judibana'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'La Cruz de Taratara'                 ]);
        App\City::create([ 'state_id' => 10, 'name' => 'La Vela de Coro'                     ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Los Taques'                          ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Maparari'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Mene de Mauroa'                      ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Mirimire'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Pedregal'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Píritu Falcón'                       ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Pueblo Nuevo Falcón'                 ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Puerto Cumarebo'                     ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Punta Cardón'                        ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Punto Fijo'                          ]);
        App\City::create([ 'state_id' => 10, 'name' => 'San Juan de Los Cayos'               ]);
        App\City::create([ 'state_id' => 10, 'name' => 'San Luis'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Santa Ana Falcón'                    ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Santa Cruz De Bucaral'               ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Tocopero'                            ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Tocuyo de La Costa'                  ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Tucacas'                             ]);
        App\City::create([ 'state_id' => 10, 'name' => 'Yaracal'                             ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Altagracia de Orituco'               ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Cabruta'                             ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Calabozo'                            ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Camaguán'                            ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Chaguaramas Guárico'                 ]);
        App\City::create([ 'state_id' => 11, 'name' => 'El Socorro'                          ]);
        App\City::create([ 'state_id' => 11, 'name' => 'El Sombrero'                         ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Las Mercedes de Los Llanos'          ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Lezama'                              ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Onoto'                               ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Ortíz'                               ]);
        App\City::create([ 'state_id' => 11, 'name' => 'San José de Guaribe'                 ]);
        App\City::create([ 'state_id' => 11, 'name' => 'San Juan de Los Morros'              ]);
        App\City::create([ 'state_id' => 11, 'name' => 'San Rafael de Laya'                  ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Santa María de Ipire'                ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Tucupido'                            ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Valle de La Pascua'                  ]);
        App\City::create([ 'state_id' => 11, 'name' => 'Zaraza'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Aguada Grande'                       ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Atarigua'                            ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Barquisimeto'                        ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Bobare'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Cabudare'                            ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Carora'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Cubiro'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Cují'                                ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Duaca'                               ]);
        App\City::create([ 'state_id' => 12, 'name' => 'El Manzano'                          ]);
        App\City::create([ 'state_id' => 12, 'name' => 'El Tocuyo'                           ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Guaríco'                             ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Humocaro Alto'                       ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Humocaro Bajo'                       ]);
        App\City::create([ 'state_id' => 12, 'name' => 'La Miel'                             ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Moroturo'                            ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Quíbor'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Río Claro'                           ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Sanare'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Santa Inés'                          ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Sarare'                              ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Siquisique'                          ]);
        App\City::create([ 'state_id' => 12, 'name' => 'Tintorero'                           ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Apartaderos Mérida'                  ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Arapuey'                             ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Bailadores'                          ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Caja Seca'                           ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Canaguá'                             ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Chachopo'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Chiguara'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Ejido'                               ]);
        App\City::create([ 'state_id' => 13, 'name' => 'El Vigía'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'La Azulita'                          ]);
        App\City::create([ 'state_id' => 13, 'name' => 'La Playa'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Lagunillas Mérida'                   ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Mérida'                              ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Mesa de Bolívar'                     ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Mucuchíes'                           ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Mucujepe'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Mucuruba'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Nueva Bolivia'                       ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Palmarito'                           ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Pueblo Llano'                        ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Santa Cruz de Mora'                  ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Santa Elena de Arenales'             ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Santo Domingo'                       ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Tabáy'                               ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Timotes'                             ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Torondoy'                            ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Tovar'                               ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Tucani'                              ]);
        App\City::create([ 'state_id' => 13, 'name' => 'Zea'                                 ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Araguita'                            ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Carrizal'                            ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Caucagua'                            ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Chaguaramas Miranda'                 ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Charallave'                          ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Chirimena'                           ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Chuspa'                              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Cúa'                                 ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Cupira'                              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Curiepe'                             ]);
        App\City::create([ 'state_id' => 14, 'name' => 'El Guapo'                            ]);
        App\City::create([ 'state_id' => 14, 'name' => 'El Jarillo'                          ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Filas de Mariche'                    ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Guarenas'                            ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Guatire'                             ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Higuerote'                           ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Los Anaucos'                         ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Los Teques'                          ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Ocumare del Tuy'                     ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Panaquire'                           ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Paracotos'                           ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Río Chico'                           ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San Antonio de Los Altos'            ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San Diego de Los Altos'              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San Fernando del Guapo'              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San Francisco de Yare'               ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San José de Los Altos'               ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San José de Río Chico'               ]);
        App\City::create([ 'state_id' => 14, 'name' => 'San Pedro de Los Altos'              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Santa Lucía'                         ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Santa Teresa'                        ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Tacarigua de La Laguna'              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Tacarigua de Mamporal'               ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Tácata'                              ]);
        App\City::create([ 'state_id' => 14, 'name' => 'Turumo'                              ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Aguasay'                             ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Aragua de Maturín'                   ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Barrancas del Orinoco'               ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Caicara de Maturín'                  ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Caripe'                              ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Caripito'                            ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Chaguaramal'                         ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Chaguaramas Monagas'                 ]);
        App\City::create([ 'state_id' => 15, 'name' => 'El Furrial'                          ]);
        App\City::create([ 'state_id' => 15, 'name' => 'El Tejero'                           ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Jusepín'                             ]);
        App\City::create([ 'state_id' => 15, 'name' => 'La Toscana'                          ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Maturín'                             ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Miraflores'                          ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Punta de Mata'                       ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Quiriquire'                          ]);
        App\City::create([ 'state_id' => 15, 'name' => 'San Antonio de Maturín'              ]);
        App\City::create([ 'state_id' => 15, 'name' => 'San Vicente Monagas'                 ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Santa Bárbara'                       ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Temblador'                           ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Teresen'                             ]);
        App\City::create([ 'state_id' => 15, 'name' => 'Uracoa'                              ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Altagracia'                          ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Boca de Pozo'                        ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Boca de Río'                         ]);
        App\City::create([ 'state_id' => 16, 'name' => 'El Espinal'                          ]);
        App\City::create([ 'state_id' => 16, 'name' => 'El Valle del Espíritu Santo'         ]);
        App\City::create([ 'state_id' => 16, 'name' => 'El Yaque'                            ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Juangriego'                          ]);
        App\City::create([ 'state_id' => 16, 'name' => 'La Asunción'                         ]);
        App\City::create([ 'state_id' => 16, 'name' => 'La Guardia'                          ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Pampatar'                            ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Porlamar'                            ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Puerto Fermín'                       ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Punta de Piedras'                    ]);
        App\City::create([ 'state_id' => 16, 'name' => 'San Francisco de Macanao'            ]);
        App\City::create([ 'state_id' => 16, 'name' => 'San Juan Bautista'                   ]);
        App\City::create([ 'state_id' => 16, 'name' => 'San Pedro de Coche'                  ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Santa Ana de Nueva Esparta'          ]);
        App\City::create([ 'state_id' => 16, 'name' => 'Villa Rosa'                          ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Acarigua'                            ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Agua Blanca'                         ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Araure'                              ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Biscucuy'                            ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Boconoito'                           ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Campo Elías'                         ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Chabasquén'                          ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Guanare'                             ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Guanarito'                           ]);
        App\City::create([ 'state_id' => 17, 'name' => 'La Aparición'                        ]);
        App\City::create([ 'state_id' => 17, 'name' => 'La Misión'                           ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Mesa de Cavacas'                     ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Ospino'                              ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Papelón'                             ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Payara'                              ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Pimpinela'                           ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Píritu de Portuguesa'                ]);
        App\City::create([ 'state_id' => 17, 'name' => 'San Rafael de Onoto'                 ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Santa Rosalía'                       ]);
        App\City::create([ 'state_id' => 17, 'name' => 'Turén'                               ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Altos de Sucre'                      ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Araya'                               ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Cariaco'                             ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Carúpano'                            ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Casanay'                             ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Cumaná'                              ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Cumanacoa'                           ]);
        App\City::create([ 'state_id' => 18, 'name' => 'El Morro Puerto Santo'               ]);
        App\City::create([ 'state_id' => 18, 'name' => 'El Pilar'                            ]);
        App\City::create([ 'state_id' => 18, 'name' => 'El Poblado'                          ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Guaca'                               ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Guiria'                              ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Irapa'                               ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Manicuare'                           ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Mariguitar'                          ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Río Caribe'                          ]);
        App\City::create([ 'state_id' => 18, 'name' => 'San Antonio del Golfo'               ]);
        App\City::create([ 'state_id' => 18, 'name' => 'San José de Aerocuar'                ]);
        App\City::create([ 'state_id' => 18, 'name' => 'San Vicente de Sucre'                ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Santa Fe de Sucre'                   ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Tunapuy'                             ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Yaguaraparo'                         ]);
        App\City::create([ 'state_id' => 18, 'name' => 'Yoco'                                ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Abejales'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Borota'                              ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Bramon'                              ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Capacho'                             ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Colón'                               ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Coloncito'                           ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Cordero'                             ]);
        App\City::create([ 'state_id' => 19, 'name' => 'El Cobre'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'El Pinal'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Independencia'                       ]);
        App\City::create([ 'state_id' => 19, 'name' => 'La Fría'                             ]);
        App\City::create([ 'state_id' => 19, 'name' => 'La Grita'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'La Pedrera'                          ]);
        App\City::create([ 'state_id' => 19, 'name' => 'La Tendida'                          ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Las Delicias'                        ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Las Hernández'                       ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Lobatera'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Michelena'                           ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Palmira'                             ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Pregonero'                           ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Queniquea'                           ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Rubio'                               ]);
        App\City::create([ 'state_id' => 19, 'name' => 'San Antonio del Tachira'             ]);
        App\City::create([ 'state_id' => 19, 'name' => 'San Cristobal'                       ]);
        App\City::create([ 'state_id' => 19, 'name' => 'San José de Bolívar'                 ]);
        App\City::create([ 'state_id' => 19, 'name' => 'San Josecito'                        ]);
        App\City::create([ 'state_id' => 19, 'name' => 'San Pedro del Río'                   ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Santa Ana Táchira'                   ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Seboruco'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Táriba'                              ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Umuquena'                            ]);
        App\City::create([ 'state_id' => 19, 'name' => 'Ureña'                               ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Batatal'                             ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Betijoque'                           ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Boconó'                              ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Carache'                             ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Chejende'                            ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Cuicas'                              ]);
        App\City::create([ 'state_id' => 20, 'name' => 'El Dividive'                         ]);
        App\City::create([ 'state_id' => 20, 'name' => 'El Jaguito'                          ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Escuque'                             ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Isnotú'                              ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Jajó'                                ]);
        App\City::create([ 'state_id' => 20, 'name' => 'La Ceiba'                            ]);
        App\City::create([ 'state_id' => 20, 'name' => 'La Concepción de Trujllo'            ]);
        App\City::create([ 'state_id' => 20, 'name' => 'La Mesa de Esnujaque'                ]);
        App\City::create([ 'state_id' => 20, 'name' => 'La Puerta'                           ]);
        App\City::create([ 'state_id' => 20, 'name' => 'La Quebrada'                         ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Mendoza Fría'                        ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Meseta de Chimpire'                  ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Monay'                               ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Motatán'                             ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Pampán'                              ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Pampanito'                           ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Sabana de Mendoza'                   ]);
        App\City::create([ 'state_id' => 20, 'name' => 'San Lázaro'                          ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Santa Ana de Trujillo'               ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Tostós'                              ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Trujillo'                            ]);
        App\City::create([ 'state_id' => 20, 'name' => 'Valera'                              ]);
        App\City::create([ 'state_id' => 21, 'name' => 'Carayaca'                            ]);
        App\City::create([ 'state_id' => 21, 'name' => 'Litoral'                             ]);
        App\City::create([ 'state_id' => 21, 'name' => 'La Guaira'                           ]);
        App\City::create([ 'state_id' => 21, 'name' => 'Catia La Mar'                        ]);
        App\City::create([ 'state_id' => 21, 'name' => 'Macuto'                              ]);
        App\City::create([ 'state_id' => 21, 'name' => 'Naiguatá'                            ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Archipiélago Los Roques'             ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Aroa'                                ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Boraure'                             ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Campo Elías de Yaracuy'              ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Chivacoa'                            ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Cocorote'                            ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Farriar'                             ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Guama'                               ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Marín'                               ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Nirgua'                              ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Sabana de Parra'                     ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Salom'                               ]);
        App\City::create([ 'state_id' => 22, 'name' => 'San Felipe'                          ]);
        App\City::create([ 'state_id' => 22, 'name' => 'San Pablo de Yaracuy'                ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Urachiche'                           ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Yaritagua'                           ]);
        App\City::create([ 'state_id' => 22, 'name' => 'Yumare'                              ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Bachaquero'                          ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Bobures'                             ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Cabimas'                             ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Campo Concepción'                    ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Campo Mara'                          ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Campo Rojo'                          ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Carrasquero'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Casigua'                             ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Chiquinquirá'                        ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Ciudad Ojeda'                        ]);
        App\City::create([ 'state_id' => 23, 'name' => 'El Batey'                            ]);
        App\City::create([ 'state_id' => 23, 'name' => 'El Carmelo'                          ]);
        App\City::create([ 'state_id' => 23, 'name' => 'El Chivo'                            ]);
        App\City::create([ 'state_id' => 23, 'name' => 'El Guayabo'                          ]);
        App\City::create([ 'state_id' => 23, 'name' => 'El Mene'                             ]);
        App\City::create([ 'state_id' => 23, 'name' => 'El Venado'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Encontrados'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Gibraltar'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Isla de Toas'                        ]);
        App\City::create([ 'state_id' => 23, 'name' => 'La Concepción del Zulia'             ]);
        App\City::create([ 'state_id' => 23, 'name' => 'La Paz'                              ]);
        App\City::create([ 'state_id' => 23, 'name' => 'La Sierrita'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Lagunillas del Zulia'                ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Las Piedras de Perijá'               ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Los Cortijos'                        ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Machiques'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Maracaibo'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Mene Grande'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Palmarejo'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Paraguaipoa'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Potrerito'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Pueblo Nuevo del Zulia'              ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Puertos de Altagracia'               ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Punta Gorda'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Sabaneta de Palma'                   ]);
        App\City::create([ 'state_id' => 23, 'name' => 'San Francisco'                       ]);
        App\City::create([ 'state_id' => 23, 'name' => 'San José de Perijá'                  ]);
        App\City::create([ 'state_id' => 23, 'name' => 'San Rafael del Moján'                ]);
        App\City::create([ 'state_id' => 23, 'name' => 'San Timoteo'                         ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Santa Bárbara Del Zulia'             ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Santa Cruz de Mara'                  ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Santa Cruz del Zulia'                ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Santa Rita'                          ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Sinamaica'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Tamare'                              ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Tía Juana'                           ]);
        App\City::create([ 'state_id' => 23, 'name' => 'Villa del Rosario'                   ]);
        App\City::create([ 'state_id' => 24, 'name' => 'Caracas'                             ]);
        App\City::create([ 'state_id' => 24, 'name' => 'El Junquito'                         ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Archipiélago Los Monjes'             ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Isla La Tortuga y Cayos adyacentes'  ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Isla La Sola'                        ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Islas Los Testigos'                  ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Islas Los Frailes'                   ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Isla La Orchila'                     ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Archipiélago Las Aves'               ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Isla de Aves'                        ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Isla La Blanquilla'                  ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Isla de Patos'                       ]);
        App\City::create([ 'state_id' => 25, 'name' => 'Islas Los Hermanos'                  ]);
    }
}
